mysql:
    image: mysql
    environment:
        MYSQL_USER: "ghost"
        MYSQL_PASSWORD: "password"
        MYSQL_DATABASE: "ghost"
        MYSQL_ROOT_PASSWORD: "supersecret"
ghost:
    links:
    - haproxy:db
    image: dockerfile/ghost
    volumes:
    - ghost:/ghost-override
    environment:
        VIRTUAL_HOST: "b2d.dev"
nginx:
    links:
    - ghost:app
    ports:
    - "80:80"
    image: dockerfile/nginx
    volumes:
    - nginx/sites-enabled:/etc/nginx/sites-enabled
haproxy:
    image: dockerfile/haproxy
    ports:
    - "3306:3306"
    volumes:
    - haproxy:/haproxy-override/
    links:
    - mysql:db
    environment:
        MYSQL_USER: "ghost"
        MYSQL_PASSWORD: "password"
        MYSQL_DATABASE: "ghost"
